### ISSUE TITLE
model.breaks result interpretation

### ISSUE THREAD

**Issue by nicomatton** [gieseke/bfast#1]
Hey there !

Thanks for the python implementation of the bfast algo !
However, I'm still a bit confused about the results of the "model.breaks" array.
What are the meanings of the values "-2", "-1", etc.
I guess that the positive values corresponds to the index of the image where the break is detected ?

Thanks for the clarifications !

**Comment by gieseke** [comment]
Hi

very good point, I think this was not mentioned in the documentation yet. Sorry about that.

- A -2 corresponds to pixels for which not sufficient non-NaN values are available (less than 5 values)
- A -1 corresponds to "no break detected"
- An idx>=0 corresponds to the first break in the monitoring period detected by BFASTMonitor.

I have added a more detailed description to both the breaks and the means property of the BFASTMonitor class (to the develop branch). Will be part of the next release. 

You can also have a look examples/peru_small_opencl.py, which illustrates the breaks and means a bit more.

Thanks again,
Fabian

**Comment by nicomatton** [comment]
Thank you very much ! Very clear now !
