### ISSUE TITLE
Magnitudes for openCL

### ISSUE THREAD

**Issue by Carolina710** [gieseke/bfast#10]
### Hello, do you have any idea when the magnitude calculation for the openCL version will be available?
I'm using the y_error and the ns values that are returned from bfastfinaldetailed, but it takes some time to do the calculation on the CPU, as well as a large allocation of GPU memory necessary to perform the bfastfinaldetailed. I have already looked at the bfastfinal and bfastfinaldetailed files a lot, trying to understand which kernels do what, but they are very unreadable.
I saw that you made commits to the opencl-backend-debug branch with work for magnitude calculation for the openCL, but I was unable to use the updates.

Thank you!

**Comment by mortvest** [comment]
Hi Carolina,

There has been a lot of changes to the OpenCL version, and we are working on tuning its performance and it would take a while.
In a meantime you can use opencl-backend-debug branch. It supports the magnitudes for both the OpenCL and Python backends. What problems are you experiencing with installing it?

**Comment by Carolina710** [comment]
Thank you for the rapid response.

I just used your peru_small_opencl example. The error occurs in the openCL version:

![image](https://user-images.githubusercontent.com/54868087/100238180-ce853b00-2f27-11eb-963b-ad426967c015.png)

I wonder if it is not related to the _get_futhark_params function, that is returning null?

![image](https://user-images.githubusercontent.com/54868087/100238403-10ae7c80-2f28-11eb-957a-da7cc02ecf79.png)

Thank you! :)

**Comment by mortvest** [comment]
That looks like an internal OpenCL problem. _get_futhark_params() should not be a problem, since returns an empty dictionary here, hence no tuning is applied. I don't get this error when running the peru_small_opencl.py and it runs fine for me. 
What GPU are you using?

**Comment by Carolina710** [comment]
Hello,

My GPU is quit of lower performance:

![image](https://user-images.githubusercontent.com/54868087/100259056-adc8df80-2f3f-11eb-824e-1aa62b846075.png)

After your response, I take some time to run the code on a remote PC that I have access and all works fine. 👍 

![image](https://user-images.githubusercontent.com/54868087/100277269-cd213600-2f5a-11eb-83a1-035ec87b0111.png)

Thank you!

**Comment by mortvest** [comment]
No problem. I have also experienced similar issues with my old laptop after we have changed the indexing to 64-bit integers.

**Comment by mortvest** [comment]
OpenCL magnitude support has been added to [develop](https://github.com/gieseke/bfast/tree/develop)
