### ISSUE TITLE
pyhton backend n_chunk is never used 

### ISSUE THREAD

**Issue by 12rambau** [gieseke/bfast#30]
I checked the file https://github.com/diku-dk/bfast/blob/master/bfast/monitor/python/base.py and the `n_chunks` parameter of the fit function is never used.
Do you prefer to implement a chunk loop or discard the parameter ?

**Comment by mortvest** [comment]
It should definitely not have a chunk loop. This can be fixed it in the boilerplate, so that we keep the same API for all backends, but the parameter would be ignored.

**Comment by mortvest** [comment]
Fixed

**Comment by 12rambau** [comment]
Can you point me to the commit that implemented the change ? It useful to follow up with your devs and to pull this kind of improvement in my branches. 

If you have not yet pushed the modification to github, would you mind letting the issue open, for me closing means both "fixed" and "available to developers".
