### ISSUE TITLE
why _model is reset each time fit is called ? 

### ISSUE THREAD

**Issue by 12rambau** [gieseke/bfast#31]
> I would create one instance of BFASTMonitor for each GPU (you can use device_id to choose GPU), then run fit() on each window. Alternatively, you can use bigger windows, and use n_chunks, to let BFASTMonitor split the window into smaller chunks. Depends on the size of the datasets that you are using and the available RAM.

I checked the `BFASTMonitor` object and `_model` is not set once and for all when `BFASTMonitor` is instantiated but every time the `fit` method is called. Meaning that for GPU implementation the setting of the device is reset every time. 

I don't see any parameter relative to the `_model` in the the `fit` method, wouldn't it be more semantic to move it to the `__init__` method ? 

Happy to create a PR

**Comment by mortvest** [comment]
That is a actually an interesting question. I didn't write this part of the code, so I need to look into that.

**Comment by mortvest** [comment]
It is actually a problem, nice catch. Fixed it.

**Comment by 12rambau** [comment]
Can you point me to the commit that implemented the change ? It useful to follow up with your devs and to pull this kind of improvement in my branches. 

If you have not yet pushed the modification to github, would you mind letting the issue open, for me closing means both "fixed" and "available to developers".
