### ISSUE TITLE
IndexError: index -54 is out of bounds

### ISSUE THREAD

**Issue by Carolina710** [gieseke/bfast#7]
Hello,

I share "Tile_1" data: https://drive.google.com/drive/folders/15DK5T9hZUaaIBNsfzR3tTp5pFb9XCWt5?usp=sharing

Using this data, an error occurs while processing row 120, in the Python version. This error does not always happen, in this case, it happens when I use start_monitor = datetime(2018, 6, 18), for example. If you try start_monitor = datetime(2016, 1, 1) everything work fine.

The error is the follow:

![image](https://user-images.githubusercontent.com/54868087/98695515-a368ec00-236a-11eb-97e7-243eae074c89.png)

But running in OpenCL I can obtain results.

You can use this gist: https://gist.github.com/Carolina710/330b473478dd59188edaaa6a3fd76bb6 to work with Tile_1.

Thank you!

**Comment by mortvest** [comment]
I have run the gist that you have provided. The error does not seem to occur on the [develop branch](https://github.com/gieseke/bfast/tree/develop). It was probably fixed with the other bugs with the python backend. Could you check if it is the case for you as well?

**Comment by Carolina710** [comment]
Hi! Yes, it works well for me too. Thank you very much, and thank you for adding the magnitude calculation! I will continue to work around the library, and any other issues I may find, I will let you know!

**Comment by mortvest** [comment]
[fixed](https://github.com/gieseke/bfast/tree/develop)
